name: GitHub Actions Demo 2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issue_comment:
    types: [created]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@trigger'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"success"} 
      
      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test run'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}