name: GitHub Actions Demo 2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issue_comment:
    types: [created]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@trigger'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        
      - uses: actions/create-outputs@v0.0.0-fake
        if: always()
        id: test

      - uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{ steps.test.outputs.summary }}"} 

      - run: 'echo dupa'
        if: steps.check.outputs.triggered == 'true' 
      
