name: GitHub Actions Demo 2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
  push:
  issue_comment:
    types: [created]

jobs:
  
  deploy:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:

      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@trigger'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true' 